### ISSUE TITLE
Help with migration from WaitAsync() -> ConfigureAwait

### ISSUE THREAD

**Issue by drew-512** [timcassell/ProtoPromise#498]
Hi Tim, excited and grateful for the 3.2.0 release.  Way to go!

Still looking forward to surprising you with the project here that makes good use of PP. 

I have an exiting call:

```csharp
waiter.Deferred.Promise.WaitAsync(SynchronizationContext.Current, forceAsync: true);
```

In the following code, but it's not clear to me how to adapt it to the `ConfigureAwait`:
```csharp
    public class ClientOp {

        ...

        // stores a deferred operation awaiting completion
        readonly struct StatusAwaiter {
            public readonly OpStatus              WaitingFor;
            public readonly Promise<Err>.Deferred Deferred;
            
            public StatusAwaiter(OpStatus status) {
                this.WaitingFor = status;
                this.Deferred   = Promise.NewDeferred<Err>();
            }
        }
        List<StatusAwaiter>  _waiters;


        // Sets the status of this ClientOp to the given status and releases any waiters that are fullfilled.
        public void                         SetStatus(OpStatus newStatus) {
            if (newStatus == _status) {
                return;
            }
            _status = newStatus;
            
            for (int i = 0; _waiters != null && i < _waiters.Count; i++) {
                var wi = _waiters[i];
                if (newStatus >= wi.WaitingFor) {
                    _waiters.RemoveAt(i);
                    i--;
                    wi.Deferred.Resolve(_lastErr);
                }
            }
            
            this.OnStatusChanged?.Invoke(this);
        } 
        

        // Allows a caller to await this ClientOp reaching a given staten.   
        // If this ClientOp is already at or past the given status, a no-cost immediate is returned.
        public Promise<Err>                 Await(OpStatus wantStatus) {
            if (this.Status >= wantStatus) {
                return Promise.Resolved<Err>(_lastErr);
            }
            var waiter = new StatusAwaiter(wantStatus);
            _waiters ??= new List<StatusAwaiter>(1);
            _waiters.Add(waiter);
            
            // forceAsync: true performs execution in the main run loop (vs from the caller's Resolve stack)
            return waiter.Deferred.Promise.WaitAsync(SynchronizationContext.Current, forceAsync: true);
            //return waiter.Deferred.Promise.ConfigureAwait(new ContinuationOptions(SynchronizationContext.Current, CompletedContinuationBehavior.Asynchronous));
        }

        ...

    }

```

**Comment by drew-512** [comment]
Ah, ok `ConfigureContinuation` was it.   I may have gotten thrown off by the `[Obsolete("Prefer ConfigureAwait", false)]` for `WaitAsync()`.

Thanks!

Love the `Channel` addition to 3.2.0, especially since my main jam is Go and will prolly have a question or two before long.

**Comment by timcassell** [comment]
Yeah, I just wrote `Prefer ConfigureAwait` because I figured `await promise` is more common than `promise.Then(...)`, and `ConfigureAwait` is more efficient for async/await then `ConfigureContinuation`, and I wanted to steer users to the more efficient method. Both methods were designed with local continuations in mind, not really for returning the promise. Because of race conditions, the behavior might not be what you expect if you do `promise.Then(() => otherPromise.ConfigureContinuation(...))`.

**Comment by timcassell** [comment]
If this is a common enough configuration, I wonder if it would make sense to add a new static property to `ContinuationOptions`.

```cs
/// <summary>
/// Returns an instance of <see cref="ContinuationOptions"/> that configures continuations to execute asynchronously on the captured context.
/// </summary>
public static ContinuationOptions Asynchronous
    => new ContinuationOptions(SynchronizationOption.CapturedContext, CompletedContinuationBehavior.Asynchronous);
```

**Comment by drew-512** [comment]
One thing I was unsure about was if PP would spawn a thread as a background one (which would be bad since I need it on main), or if there was an additional flag I was missing with 3.2.0 that was needed to resume on the main thread.  That was when I realized the name "Asynchronous" was a slightly confusing label since execution technically would not be async since the current context was in use.

**Comment by timcassell** [comment]
> One thing I was unsure about was if PP would spawn a thread as a background one

ProtoPromise never spawns threads itself. By default it uses the `ThreadPool` for the background context.

> (which would be bad since I need it on main), or if there was an additional flag I was missing with 3.2.0 that was needed to resume on the main thread.

```cs
public ContinuationOptions(SynchronizationOption continuationOption, CompletedContinuationBehavior completedContinuationBehavior)
```

The first argument `continuationOption` is the context that it will execute on. You can pass `SynchronizationOption.Foreground` if you explicitly want it to be on the main thread. Passing `SynchronizationOption.CapturedContext` or `SynchronizationContext.Current` will use the current context, which might be the main thread or a background thread.

> That was when I realized the name "Asynchronous" was a slightly confusing label since execution technically would not be async since the current context was in use.

The second argument `completedContinuationBehavior` is the behavior to use if the promise is already complete when it is awaited. `CompletedContinuationBehavior.Asynchronous` forces it to be async, using whatever context was provided as the first argument. If it is using the captured context, it will force it to be async on the same context, rather than continuing synchronously (it calls `SynchronizationContext.Post`).

**Comment by drew-512** [comment]
> The first argument continuationOption is the context that it will execute on. You can pass SynchronizationOption.Foreground if you explicitly want it to be on the main thread. Passing SynchronizationOption.CapturedContext or SynchronizationContext.Current will use the current context, which might be the main thread or a background thread.

Ah, ok, thanks.   I wasn't aware of the explicit `SynchronizationOption.Foreground` since the call site was the main thread.
